// Mock data for factories, events, and AI classification

export const MOCK_FACTORIES = {
    factory1: {
        id: 'factory1',
        name: 'GreenTech Recyclers',
        type: 'Electronics',
        logo_url: 'https://via.placeholder.com/100/2ECC71/FFFFFF?text=GT',
        rating: 4.8,
        accepts_materials: ['Electronics', 'Metal'],
        address: 'Zone Industrielle, Tunis',
    },
    factory2: {
        id: 'factory2',
        name: 'PlastiCycle Tunisia',
        type: 'Plastics',
        logo_url: 'https://via.placeholder.com/100/3B82F6/FFFFFF?text=PC',
        rating: 4.5,
        accepts_materials: ['Plastics'],
        address: 'Avenue Bourguiba, Sfax',
    },
    factory3: {
        id: 'factory3',
        name: 'MetalWorks Sousse',
        type: 'Electronics',
        logo_url: 'https://via.placeholder.com/100/F59E0B/FFFFFF?text=MW',
        rating: 4.7,
        accepts_materials: ['Metal', 'Electronics'],
        address: 'Industrial Park, Sousse',
    },
    factory4: {
        id: 'factory4',
        name: 'EcoGlass Monastir',
        type: 'Glass',
        logo_url: 'https://via.placeholder.com/100/22C55E/FFFFFF?text=EG',
        rating: 4.3,
        accepts_materials: ['Glass'],
        address: 'Coastal Road, Monastir',
    },
    factory5: {
        id: 'factory5',
        name: 'PaperMill Nabeul',
        type: 'Paper',
        logo_url: 'https://via.placeholder.com/100/A855F7/FFFFFF?text=PM',
        rating: 4.6,
        accepts_materials: ['Paper'],
        address: 'Route Principale, Nabeul',
    },
};

export const MOCK_EVENTS = {
    event1: {
        id: 'event1',
        organizer_id: 'system',
        title: '🚨 URGENT: Forest Fire Alert - Tunis Hills',
        description: 'Major fire reported in Tunis forest preserve. Immediate action needed! Firefighters need volunteers to help evacuate wildlife and create firebreaks.',
        category: 'OTHER',
        image_url: null, // Will use fire_stock.jpg from assets
        is_emergency: true,
        severity_level: 10,
        latitude: 36.86,
        longitude: 10.19,
        participants_count: 15,
        reward_amount: 5.00,
        event_date: Date.now(),
        status: 'UPCOMING',
        created_at: Date.now() - 3600000, // 1 hour ago
    },
    event2: {
        id: 'event2',
        organizer_id: 'system',
        title: 'Beach Cleanup Sunday - Hammamet',
        description: 'Join us for a relaxing beach cleanup event. Equipment provided! Bring your family and help keep our beaches beautiful.',
        category: 'BEACH_CLEANUP',
        image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400',
        is_emergency: false,
        severity_level: 0,
        latitude: 36.40,
        longitude: 10.62,
        participants_count: 78,
        reward_amount: 1.00,
        event_date: Date.now() + 86400000 * 3, // 3 days from now
        status: 'UPCOMING',
        created_at: Date.now() - 86400000 * 2,
    },
    event3: {
        id: 'event3',
        organizer_id: 'system',
        title: 'Tree Planting Marathon - Tunis Forest',
        description: 'Help us plant 500 trees! Transportation and refreshments included. Make a lasting impact on our environment.',
        category: 'TREE_PLANTING',
        image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400',
        is_emergency: false,
        severity_level: 0,
        latitude: 36.8600,
        longitude: 10.1900,
        participants_count: 124,
        reward_amount: 1.00,
        event_date: Date.now() + 86400000 * 7, // 1 week from now
        status: 'UPCOMING',
        created_at: Date.now() - 86400000 * 5,
    },
    event4: {
        id: 'event4',
        organizer_id: 'system',
        title: '⚠️ Illegal Dumping Site - Sousse Industrial Zone',
        description: 'Large illegal dump site discovered. Hazardous materials present. Need volunteers for documentation and cleanup coordination.',
        category: 'OTHER',
        image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
        is_emergency: true,
        severity_level: 8,
        latitude: 35.8288,
        longitude: 10.6405,
        participants_count: 8,
        reward_amount: 3.00,
        event_date: Date.now() + 86400000, // Tomorrow
        status: 'UPCOMING',
        created_at: Date.now() - 7200000, // 2 hours ago
    },
    event5: {
        id: 'event5',
        organizer_id: 'system',
        title: 'Community Garden Workshop - Sfax',
        description: 'Learn sustainable gardening techniques and help maintain our community garden. Seeds and tools provided!',
        category: 'COMMUNITY_GARDEN',
        image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
        is_emergency: false,
        severity_level: 0,
        latitude: 34.7406,
        longitude: 10.7603,
        participants_count: 45,
        reward_amount: 1.00,
        event_date: Date.now() + 86400000 * 5, // 5 days from now
        status: 'UPCOMING',
        created_at: Date.now() - 86400000 * 3,
    },
};

export const MOCK_ANIMALS = {
    animal1: {
        id: 'animal1',
        name: 'Luna',
        species: 'CAT',
        breed: 'Persian Mix',
        age_months: 8,
        gender: 'FEMALE',
        images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400'],
        adoption_fee: 50.00,
        status: 'AVAILABLE',
        description: 'Sweet and playful Persian mix. Loves cuddles and playing with toys. Vaccinated and neutered.',
        health_status: 'Excellent',
        is_vaccinated: true,
        is_neutered: true,
        location_city: 'Tunis',
    },
    animal2: {
        id: 'animal2',
        name: 'Max',
        species: 'DOG',
        breed: 'German Shepherd',
        age_months: 24,
        gender: 'MALE',
        images: ['https://images.unsplash.com/photo-1568572933382-74d440642117?w=400'],
        adoption_fee: 100.00,
        status: 'AVAILABLE',
        description: 'Loyal and protective German Shepherd. Great with families and children. Well-trained.',
        health_status: 'Good',
        is_vaccinated: true,
        is_neutered: true,
        location_city: 'Sfax',
    },
    animal3: {
        id: 'animal3',
        name: 'Coco',
        species: 'CAT',
        breed: 'Siamese',
        age_months: 6,
        gender: 'FEMALE',
        images: ['https://images.unsplash.com/photo-1573865526739-10c1d3a1f0cc?w=400'],
        adoption_fee: 75.00,
        status: 'AVAILABLE',
        description: 'Beautiful Siamese kitten with striking blue eyes. Very vocal and affectionate.',
        health_status: 'Excellent',
        is_vaccinated: true,
        is_neutered: false,
        location_city: 'Sousse',
    },
};

export const MOCK_CAMPAIGNS = {
    campaign1: {
        id: 'campaign1',
        creator_id: 'system',
        title: 'Rescue Stray Cats in Sousse',
        description: 'Help us provide medical care, shelter, and food for 50+ stray cats in the Sousse region. Funds will cover vaccinations, neutering, and daily meals.',
        category: 'ANIMAL_WELFARE',
        image_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
        goal_amount: 5000.00,
        current_amount: 3250.00,
        donor_count: 87,
        status: 'ACTIVE',
        created_at: Date.now() - 86400000 * 30,
    },
    campaign2: {
        id: 'campaign2',
        creator_id: 'system',
        title: 'Plant 1000 Trees in Tunis',
        description: 'Transform degraded land into thriving forest. Every donation helps us plant native trees and restore biodiversity.',
        category: 'TREE_PLANTING',
        image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400',
        goal_amount: 10000.00,
        current_amount: 7850.00,
        donor_count: 203,
        status: 'ACTIVE',
        created_at: Date.now() - 86400000 * 45,
    },
    campaign3: {
        id: 'campaign3',
        creator_id: 'system',
        title: 'Ocean Cleanup Equipment Fund',
        description: 'Purchase professional cleanup equipment for monthly beach cleaning events along the entire Tunisian coastline.',
        category: 'OCEAN_CLEANUP',
        image_url: 'https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=400',
        goal_amount: 2000.00,
        current_amount: 2000.00,
        donor_count: 65,
        status: 'FUNDED',
        created_at: Date.now() - 86400000 * 60,
    },
};

// AI Classification mappings for demo
export const AI_CLASSIFICATIONS = {
    electronics: {
        iphone: {
            category: 'Electronics',
            sub_type: 'Smartphone',
            keywords: ['iphone', 'apple', 'phone', 'mobile'],
            value_range: [150, 200],
            confidence_range: [0.91, 0.95],
        },
        android: {
            category: 'Electronics',
            sub_type: 'Smartphone',
            keywords: ['samsung', 'android', 'galaxy', 'pixel'],
            value_range: [80, 150],
            confidence_range: [0.88, 0.92],
        },
        laptop: {
            category: 'Electronics',
            sub_type: 'Laptop',
            keywords: ['laptop', 'notebook', 'dell', 'hp', 'lenovo', 'macbook'],
            value_range: [80, 150],
            confidence_range: [0.90, 0.94],
        },
        tablet: {
            category: 'Electronics',
            sub_type: 'Tablet',
            keywords: ['ipad', 'tablet', 'tab'],
            value_range: [60, 120],
            confidence_range: [0.87, 0.91],
        },
        tv: {
            category: 'Electronics',
            sub_type: 'Display',
            keywords: ['tv', 'television', 'monitor', 'screen'],
            value_range: [40, 80],
            confidence_range: [0.85, 0.90],
        },
        cable: {
            category: 'Electronics',
            sub_type: 'Cable',
            keywords: ['cable', 'usb', 'charger', 'cord', 'adapter'],
            value_range: [0.5, 3],
            confidence_range: [0.82, 0.88],
        },
        smartwatch: {
            category: 'Electronics',
            sub_type: 'Smartwatch',
            keywords: ['smartwatch', 'watch', 'wearable', 'apple watch', 'fitbit'],
            value_range: [40, 120],
            confidence_range: [0.86, 0.92],
        },
    },
    plastics: {
        bottle: {
            category: 'Plastics',
            sub_type: 'Bottle-PET',
            keywords: ['bottle', 'water', 'pet', 'beverage'],
            value_range: [0.08, 0.12],
            confidence_range: [0.92, 0.96],
            unit: 'per unit',
            quantity_range: [1, 10],
        },
        jug: {
            category: 'Plastics',
            sub_type: 'Container-HDPE',
            keywords: ['jug', 'milk', 'hdpe', 'container'],
            value_range: [0.12, 0.18],
            confidence_range: [0.90, 0.94],
            unit: 'per unit',
        },
        bag: {
            category: 'Plastics',
            sub_type: 'Bag-LDPE',
            keywords: ['bag', 'plastic', 'ldpe'],
            value_range: [0.03, 0.07],
            confidence_range: [0.85, 0.89],
            unit: 'per kg',
        },
    },
};

// Conversion rates for Impact Economy
export const CONVERSION_RATES = {
    TREE_COST: 10.00,        // $10 = 1 tree planted
    ANIMAL_COST: 5.00,       // $5 = 1 animal fed/saved
    CO2_PER_DOLLAR: 0.5,     // $1 = 0.5kg CO2 offset
    NATURE_TAX_RATE: 0.30,   // 30% of sales go to nature fund
};
